Repository CSID-DGU/2025-1-SCS4031-NOVA-S5, pull requests merged in 2025-05, with the labels that each got.

#26 feat(22): 소셜 로그인 구현
  package.json
  pnpm-lock.yaml
  public/icon/clock.svg
  public/icon/kakao-logo.svg
  public/sw.js
  src/app/api/auth/[...nextauth]/route.ts
  src/app/auth/redirect/page.tsx
  src/app/globals.css
  src/app/layout.tsx
  src/app/main/page.tsx
  src/app/page.tsx
  src/app/reward/[id]/page.tsx
  src/app/reward/page.tsx
  src/app/reward/search/page.tsx
  src/features/auth/ui/LoginContent.tsx
  src/features/auth/ui/LoginHeader.tsx
  src/features/main/ui/ChallengeCard.tsx
  src/features/main/ui/StampCard.tsx
  src/features/qrScanner/ui/UserCard.tsx
  src/features/reward/cafeDetail/ui/CafeDetailContent.tsx
  src/features/reward/cafeDetail/ui/CharacterCard.tsx
  src/features/reward/cafeDetail/ui/RewardCoupon.tsx
  src/features/reward/search/ui/SearchContent.tsx
  src/features/reward/search/ui/SearchResult.tsx
  src/features/reward/ui/RewardContent.tsx
  src/features/reward/ui/RewardHeader.tsx
  src/features/viewStampList/ui/SearchHeader.tsx
  src/middleware.ts
  src/shared/api/axios.ts
  src/shared/providers/AuthSessionProvider.tsx
  src/shared/providers/QueryProvider.tsx
  src/shared/store/rewardStore.ts
  src/shared/store/stampModalStore.ts
  src/shared/ui/GNB.tsx
  src/shared/ui/Loading.tsx
  src/shared/ui/LoadingSpinner.tsx
  src/shared/ui/StampBook.tsx
  src/shared/ui/index.ts
  src/shared/ui/modal/CafeStampModal.tsx
  src/shared/ui/modal/CafeStampModalContent.tsx
  src/shared/ui/modal/QrModal.tsx
  src/shared/ui/modal/QrSection.tsx
  src/shared/ui/modal/StampCollectModal.tsx
Labels: ✨ feature, 💄 design

#29 feat(27): 스탬프북, 카페 관련 API 연결
  package.json
  pnpm-lock.yaml
  public/sw.js
  src/app/reward/[id]/page.tsx
  src/components/ui/progress.tsx
  src/features/cafeDetail/ui/CafeStamp.tsx
  src/features/main/model/stampBookType.ts
  src/features/main/ui/StampCard.tsx
  src/features/main/ui/StampSlider.tsx
  src/features/reward/cafeDetail/ui/CafeDetailContent.tsx
  src/features/reward/cafeDetail/ui/CafeDetailHeader.tsx
  src/features/reward/cafeDetail/ui/CharacterCard.tsx
  src/features/reward/cafeDetail/ui/RewardCoupon.tsx
  src/features/reward/search/ui/SearchContent.tsx
  src/features/reward/search/ui/SearchResult.tsx
  src/features/reward/ui/StampBookList.tsx
  src/features/viewStampList/ui/ViewMode/ListSlider/LocationCard.tsx
  src/features/viewStampList/ui/ViewMode/ListSlider/LocationList.tsx
  src/features/viewStampList/ui/ViewMode/ListSlider/TopCard.tsx
  src/features/viewStampList/ui/ViewMode/ListSlider/TopList.tsx
  src/shared/api/cafe.ts
  src/shared/api/stampbook.ts
  src/shared/mocks/StampList/LocationMock.ts
  src/shared/model/CafeInfoProps.ts
  src/shared/store/cafeInfoStore.ts
  src/shared/store/stampBookStore.ts
  src/shared/ui/CafeInfo.tsx
  src/shared/ui/StampBook.tsx
  src/shared/ui/modal/CafeStampModal.tsx
Labels: ✨ feature

#35 feat(32) : 사장님 main 적립 페이지 구현
  package.json
  pnpm-lock.yaml
  public/icon/evaluation.svg
  public/icon/ownerGNB/challenge-active.svg
  public/icon/ownerGNB/challenge.svg
  public/icon/ownerGNB/design-active.svg
  public/icon/ownerGNB/design.svg
  public/icon/ownerGNB/home-active.svg
  public/icon/ownerGNB/home.svg
  public/icon/ownerGNB/mypage-active.svg
  public/icon/ownerGNB/mypage.svg
  public/img/fadedCharacter/beige.svg
  public/img/fadedCharacter/green.svg
  public/img/fadedCharacter/orange.svg
  public/img/fadedCharacter/yellow.svg
  public/img/qr/green-qr.svg
  public/img/qr/qr-comment.svg
  public/img/qr/qr-info.svg
  public/sw.js
  src/app/customer/page.tsx
  src/app/owner/main/page.tsx
  src/app/owner/qrscan/page.tsx
  src/features/customerInfo/model/index.ts
  src/features/customerInfo/model/validation.ts
  src/features/customerInfo/ui/ChallengeCard.tsx
  src/features/customerInfo/ui/ChallengeInfo.tsx
  src/features/customerInfo/ui/CustomerCard.tsx
  src/features/customerInfo/ui/CustomerHeader.tsx
  src/features/customerInfo/ui/CustomerStamp.tsx
  src/features/customerInfo/ui/CustomerTabBar.tsx
  src/features/customerInfo/ui/History.tsx
  src/features/customerInfo/ui/InfoModeSwitcher.tsx
  src/features/customerInfo/ui/RewardInfo.tsx
  src/features/customerInfo/ui/StampInfo.tsx
  src/features/customerInfo/ui/index.ts
  src/features/customerInfo/ui/modal/CancelModal.tsx
  src/features/customerInfo/ui/modal/SaveModal.tsx
  src/features/owner/ui/AddCafeCard.tsx
  src/features/owner/ui/AddStampbook.tsx
  src/features/owner/ui/CafeBottomsheet.tsx
  src/features/owner/ui/DashBoardHeader.tsx
  src/features/owner/ui/QRScanner.tsx
  src/features/owner/ui/QrCard.tsx
  src/features/owner/ui/QrScanHeader.tsx
  src/features/owner/ui/index.ts
  src/features/viewStampList/ui/LocationSheet.tsx
  src/features/viewStampList/ui/SearchHeader.tsx
  src/features/viewStampList/ui/index.ts
  src/shared/store/cancelStore.ts
  src/shared/store/index.ts
  src/shared/store/infoModeStore.ts
  src/shared/store/qrStore.ts
  src/shared/ui/BottomSheet/BottomSheet.tsx
  src/shared/ui/BottomSheet/Content.tsx
  src/shared/ui/BottomSheet/Header.tsx
  src/shared/ui/BottomSheet/Overlay.tsx
  src/shared/ui/BottomSheet/Wrapper.tsx
  src/shared/ui/BottomSheet/index.ts
  src/shared/ui/OwnerGNB.tsx
  src/shared/ui/index.ts
Labels: ✨ feature, 💄 design

#38 fix(37) : 월활한 스캔을 위한 QR 조정
  src/app/owner/qrscan/page.tsx
  src/features/owner/ui/QRScanner.tsx
  src/shared/ui/modal/QrSection.tsx
Labels: 🔧 fix

#39 feat(36) : 사장님 메인 페이지 API 연동
  .github/workflows/deploy.yml
  public/img/character/black-all.svg
  public/img/character/black-ear.svg
  public/img/character/black-face-gray.svg
  public/img/character/black-face.svg
  public/sw.js
  src/app/customer/page.tsx
  src/app/owner/main/page.tsx
  src/features/customerInfo/model/customer.type.ts
  src/features/customerInfo/model/index.ts
  src/features/customerInfo/service/api.ts
  src/features/customerInfo/service/index.ts
  src/features/customerInfo/ui/ChallengeInfo.tsx
  src/features/customerInfo/ui/CustomerCard.tsx
  src/features/customerInfo/ui/CustomerHeader.tsx
  src/features/customerInfo/ui/CustomerStamp.tsx
  src/features/customerInfo/ui/InfoModeSwitcher.tsx
  src/features/customerInfo/ui/RewardInfo.tsx
  src/features/customerInfo/ui/StampInfo.tsx
  src/features/customerInfo/ui/modal/CancelModal.tsx
  src/features/customerInfo/ui/modal/SaveModal.tsx
  src/features/fortuneWidget/ui/FortuneCard.tsx
  src/features/owner/service/api.ts
  src/features/owner/service/index.ts
  src/features/owner/ui/CafeBottomsheet.tsx
  src/features/owner/ui/DashBoardHeader.tsx
  src/shared/api/axios.ts
Labels: ✨ feature

#40 feat(34): 사장 스탬프북 페이지 UI 및 API 연결
  public/icon/bin.svg
  public/icon/hamburger.svg
  public/icon/palette.svg
  public/icon/pencil.svg
  public/img/character/green-ear.svg
  src/app/auth/redirect/page.tsx
  src/app/owner/stampbook/create/page.tsx
  src/app/owner/stampbook/info/page.tsx
  src/app/owner/stampbook/page.tsx
  src/app/owner/stampbook/template/page.tsx
  src/features/main/ui/StampSlider.tsx
  src/features/ownerStampBook/create/ui/CreateContent.tsx
  src/features/ownerStampBook/create/ui/CreateHeader.tsx
  src/features/ownerStampBook/create/ui/index.ts
  src/features/ownerStampBook/info/ui/InfoForm.tsx
  src/features/ownerStampBook/info/ui/InfoHeader.tsx
  src/features/ownerStampBook/template/ui/CharacterCard.tsx
  src/features/ownerStampBook/template/ui/StampBack.tsx
  src/features/ownerStampBook/template/ui/StampFront.tsx
  src/features/ownerStampBook/template/ui/TemplateContent.tsx
  src/features/ownerStampBook/template/ui/TemplateFooter.tsx
  src/features/ownerStampBook/template/ui/TemplateHeader.tsx
  src/features/ownerStampBook/template/ui/index.ts
  src/features/ownerStampBook/ui/CharacterBgCard.tsx
  src/features/ownerStampBook/ui/Chip.tsx
  src/features/ownerStampBook/ui/OwnerStampBook.tsx
  src/features/ownerStampBook/ui/StampBookHeader.tsx
  src/features/ownerStampBook/ui/StampBookList.tsx
  src/features/reward/cafeDetail/ui/CharacterCard.tsx
  src/features/storeRegister/model/RegisterCafe.ts
  src/features/storeRegister/ui/StoreRegisterForm.tsx
  src/lib/storeRegisterSchema.ts
  src/shared/api/cafe.ts
  src/shared/api/stampbook.ts
  src/shared/constants/dropdown.ts
  src/shared/store/cafeInfoStore.ts
  src/shared/store/roleStore.ts
  src/shared/store/stampBookStore.ts
  src/shared/store/stampEditStore.ts
  src/shared/ui/Dropdown.tsx
  src/shared/ui/OwnerGNB.tsx
  src/shared/ui/modal/CafeRegisterModal.tsx
  src/shared/ui/modal/InputModal.tsx
Labels: ✨ feature, 💄 design

#43 feat(41) : 사장 챌린지 관리 UI 구현
  package.json
  pnpm-lock.yaml
  public/icon/challenge/date.svg
  public/icon/challenge/join.svg
  public/icon/challenge/progress.svg
  public/icon/challenge/qrcode.svg
  public/icon/challenge/reward.svg
  public/icon/challenge/success.svg
  public/icon/plus.svg
  public/icon/speech/green-bubble.svg
  public/icon/speech/orange-bubble.svg
  public/icon/speech/white-line.svg
  public/icon/speech/yellow-bubble.svg
  src/app/challenge/[id]/page.tsx
  src/app/challenge/create/page.tsx
  src/app/challenge/page.tsx
  src/app/challenge/preview/page.tsx
  src/components/ui/calendar.tsx
  src/components/ui/popover.tsx
  src/components/ui/progress.tsx
  src/components/ui/select.tsx
  src/features/cafeOwnerChallenge/model/challenge.type.ts
  src/features/cafeOwnerChallenge/model/index.ts
  src/features/cafeOwnerChallenge/model/mockChallenges.ts
  src/features/cafeOwnerChallenge/ui/ChallengeCard.tsx
  src/features/cafeOwnerChallenge/ui/ChallengeTab.tsx
  src/features/cafeOwnerChallenge/ui/PlusButton.tsx
  src/features/cafeOwnerChallenge/ui/StartChallenge.tsx
  src/features/cafeOwnerChallenge/ui/index.ts
  src/features/cafeOwnerChallenge/utils/getChallengeDay.ts
  src/features/cafeOwnerChallenge/utils/getChallengeInfo.ts
  src/features/cafeOwnerChallenge/utils/getChallengeStatus.ts
  src/features/cafeOwnerChallenge/utils/index.ts
  src/features/challenge/ui/index.ts
  src/features/challenge/ui/owner/ChallengeStatus.tsx
  src/features/challenge/ui/owner/NoticeCard.tsx
  src/features/challenge/ui/owner/index.ts
  src/features/challengePreview/ui/Preview.tsx
  src/features/challengePreview/ui/index.ts
  src/features/createChallenge/ui/CreateForm.tsx
  src/features/createChallenge/ui/DatePicker.tsx
  src/features/createChallenge/ui/FileUploader.tsx
  src/features/createChallenge/ui/index.ts
  src/shared/index.ts
  src/shared/store/createChallengeStore.ts
  src/shared/ui/CloseHeader.tsx
  src/shared/ui/challenge/CertificationCard.tsx
  src/shared/ui/challenge/ChallengeInfo.tsx
  src/shared/ui/challenge/ChallengeProgress.tsx
  src/shared/ui/challenge/index.ts
  src/shared/ui/index.ts
  src/shared/utils/getChallengeType.ts
  src/shared/utils/index.ts
Labels: ✨ feature, 💄 design

#48 feat(42): 스탬프북 커스텀 기능 구현 및 스탬프북 등록 API
  package.json
  pnpm-lock.yaml
  public/fonts/NotoSans-Bold.woff2
  public/fonts/NotoSans-Medium.woff2
  public/fonts/NotoSans-Regular.woff2
  public/fonts/Pretendard-Bold.woff2
  public/fonts/Pretendard-Medium.woff2
  public/fonts/Pretendard-Regular.woff2
  public/fonts/Pretendard-SemiBold.woff2
  public/fonts/SUIT-Bold.woff2
  public/fonts/SUIT-Medium.woff2
  public/fonts/SUIT-Regular.woff2
  public/fonts/SUIT-SemiBold.woff2
  public/icon/customNav/background.svg
  public/icon/customNav/text.svg
  public/icon/plus.svg
  public/icon/redo.svg
  public/icon/undo.svg
  public/img/silhouette/black.svg
  public/sw.js
  src/app/owner/stampbook/create/page.tsx
  src/app/owner/stampbook/custom/page.tsx
  src/app/owner/stampbook/example/page.tsx
  src/app/owner/stampbook/info/page.tsx
  src/app/stamplist/[id]/page.tsx
  src/features/cafeDetail/ui/CafeCharacter.tsx
  src/features/cafeDetail/ui/CafeStamp.tsx
  src/features/cafeDetail/ui/RewardCard.tsx
  src/features/owner/ui/AddCafeCard.tsx
  src/features/ownerStampBook/custom/ui/ColorPicker.tsx
  src/features/ownerStampBook/custom/ui/CustomContent.tsx
  src/features/ownerStampBook/custom/ui/CustomHeader.tsx
  src/features/ownerStampBook/custom/ui/CustomMenu.tsx
  src/features/ownerStampBook/custom/ui/CustomStampBack.tsx
  src/features/ownerStampBook/custom/ui/CustomStampFront.tsx
  src/features/ownerStampBook/custom/ui/SideSelectModal.tsx
  src/features/ownerStampBook/custom/ui/TextBottomSheet.tsx
  src/features/ownerStampBook/example/model/cafe.ts
  src/features/ownerStampBook/example/ui/ExampleContent.tsx
  src/features/ownerStampBook/example/ui/ExampleHeader.tsx
  src/features/ownerStampBook/info/ui/InfoForm.tsx
  src/features/ownerStampBook/template/ui/CharacterCard.tsx
  src/features/ownerStampBook/ui/Hamburger.tsx
  src/features/ownerStampBook/ui/OwnerStampBook.tsx
  src/features/ownerStampBook/ui/StampBookList.tsx
  src/features/reward/ui/StampBookList.tsx
  src/features/storeRegister/ui/StoreRegisterForm.tsx
  src/lib/font-plugin.ts
  src/lib/storeRegisterSchema.ts
  src/shared/api/cafe.ts
  src/shared/api/stampbook.ts
  src/shared/hooks/useSelectedCafe.ts
  src/shared/store/cafeDetailStore.ts
  src/shared/store/createStampStore.ts
  src/shared/store/customStore.ts
  src/shared/store/roleStore.ts
  src/shared/store/stampEditStore.ts
  src/shared/ui/BottomSheet/Overlay.tsx
  src/shared/ui/StampBook.tsx
  src/shared/utils/date.ts
Labels: ✨ feature, 💄 design

#50 fix(47) : QA 수정사항 반영
  public/img/silhouette/black-silhouette.svg
  public/img/silhouette/green-silhouette.svg
  public/img/silhouette/orange-silhouette.svg
  public/img/silhouette/yellow-silhouette.svg
  src/app/owner/main/page.tsx
  src/app/stamplist/[id]/page.tsx
  src/features/cafeDetail/model/cafeDetail.type.ts
  src/features/cafeDetail/ui/CafeCharacter.tsx
  src/features/owner/ui/AddStampbook.tsx
  src/features/owner/ui/CafeBottomsheet.tsx
  src/features/owner/ui/QRScanner.tsx
  src/features/qrScanner/ui/UserCard.tsx
  src/shared/ui/CafeInfo.tsx
  src/shared/ui/Header.tsx
Labels: 🐛 bug, 🔧 fix
