Repository CSID-DGU/2025-1-SCS4031-NOVA-S5, pull requests merged in 2025-06, with the labels that each got.

#53 feat(45) : 고객 챌린지 ui 퍼블리싱
  src/app/challenge/page.tsx
  src/app/myChallenge/[id]/page.tsx
  src/app/myChallenge/page.tsx
  src/features/cafeDetail/ui/CafeCharacter.tsx
  src/features/cafeDetail/ui/CafeStamp.tsx
  src/features/cafeOwnerChallenge/model/index.ts
  src/features/cafeOwnerChallenge/ui/index.ts
  src/features/cafeOwnerChallenge/utils/getChallengeInfo.ts
  src/features/cafeOwnerChallenge/utils/getChallengeStatus.ts
  src/features/cafeOwnerChallenge/utils/index.ts
  src/features/challenge/model/allChallenge.ts
  src/features/challenge/model/index.ts
  src/features/challenge/model/myChallenge.ts
  src/features/challenge/ui/ customer/index.ts
  src/features/challengePreview/ui/Preview.tsx
  src/features/main/ui/ChallengeSlider.tsx
  src/features/main/ui/StampSlider.tsx
  src/features/qrScanner/ui/UserCard.tsx
  src/features/viewStampList/ui/ViewMode/ListSlider/LocationList.tsx
  src/features/viewStampList/ui/ViewMode/ListSlider/TopList.tsx
  src/features/viewStampList/ui/ViewMode/Map/KakaoMap.tsx
  src/shared/api/qrcode.ts
  src/shared/model/challenge.type.ts
  src/shared/model/challengeData.type.ts
  src/shared/model/index.ts
  src/shared/ui/ChallengeCard.tsx
  src/shared/ui/ChallengeTab.tsx
  src/shared/ui/ProgressChallenge.tsx
  src/shared/ui/challenge/ChallengeProgress.tsx
  src/shared/ui/index.ts
  src/shared/ui/modal/QrModal.tsx
  src/shared/utils/getChallengeDay.ts
  src/shared/utils/index.ts
Labels: ✨ feature, 🔧 fix, 💄 design

#55 feat(52): 커스텀 스탬프북 불러오기 및 undo, redo 기능 추가
  next.config.ts
  public/sw.js
  src/app/reward/[id]/page.tsx
  src/app/stamplist/[id]/page.tsx
  src/features/cafeDetail/ui/CafeCharacter.tsx
  src/features/cafeDetail/ui/CafeContent.tsx
  src/features/cafeDetail/ui/CafeStamp.tsx
  src/features/cafeDetail/ui/CafeStampBook.tsx
  src/features/main/model/stampBookType.ts
  src/features/ownerStampBook/custom/hooks/uploadPresignedImage.ts
  src/features/ownerStampBook/custom/ui/CustomContent.tsx
  src/features/ownerStampBook/custom/ui/CustomHeader.tsx
  src/features/ownerStampBook/custom/ui/CustomStampBack.tsx
  src/features/ownerStampBook/custom/ui/CustomStampFront.tsx
  src/features/ownerStampBook/custom/ui/SideSelectModal.tsx
  src/features/ownerStampBook/example/ui/ExampleContent.tsx
  src/features/ownerStampBook/ui/Hamburger.tsx
  src/features/ownerStampBook/ui/OwnerStampBook.tsx
  src/features/ownerStampBook/ui/StampBookList.tsx
  src/features/reward/cafeDetail/ui/CafeDetailContent.tsx
  src/features/reward/ui/StampBookList.tsx
  src/shared/api/image.ts
  src/shared/store/cafeDetailStore.ts
  src/shared/store/createStampStore.ts
  src/shared/store/customStore.ts
  src/shared/ui/GNB.tsx
  src/shared/ui/OwnerGNB.tsx
  src/shared/ui/StampBook.tsx
  src/shared/ui/modal/Modal.tsx
Labels: ✨ feature, 💄 design

#58 fix(56): qa 수정사항 반영
  src/app/challenge/[id]/page.tsx
  src/app/challenge/page.tsx
  src/app/main/page.tsx
  src/app/owner/main/page.tsx
  src/app/owner/qrscan/page.tsx
  src/app/owner/stampbook/page.tsx
  src/app/reward/[id]/page.tsx
  src/app/reward/page.tsx
  src/app/stamplist/page.tsx
  src/features/cafeDetail/ui/CafeStamp.tsx
  src/features/ownerStampBook/custom/hooks/uploadPresignedImage.ts
  src/features/ownerStampBook/example/ui/ExampleContent.tsx
  src/features/reward/cafeDetail/ui/RewardCoupon.tsx
  src/features/reward/ui/RewardContent.tsx
  src/features/reward/ui/StampBookList.tsx
  src/features/storeRegister/ui/StoreRegisterForm.tsx
  src/lib/storeRegisterSchema.ts
  src/shared/api/image.ts
  src/shared/ui/GNB.tsx
  src/shared/ui/StampBook.tsx
Labels: 🐛 bug, 🔧 fix

#63 hotfix: 오류 수정
  src/features/cafeDetail/ui/CafeStamp.tsx
  src/features/cafeDetail/ui/CafeStampBook.tsx
Labels: 🛠️ hotfix

#65 [fix]: 오류 사항 반영
  src/app/stamplist/[id]/page.tsx
  src/features/cafeDetail/model/cafeDetail.type.ts
  src/features/cafeDetail/ui/CafeStamp.tsx
  src/features/cafeDetail/ui/CafeStampBook.tsx
  src/features/owner/ui/CafeBottomsheet.tsx
  src/features/ownerStampBook/ui/Hamburger.tsx
  src/features/ownerStampBook/ui/StampBookHeader.tsx
  src/features/ownerStampBook/ui/StampBookList.tsx
  src/features/reward/cafeDetail/ui/CafeDetailContent.tsx
  src/features/reward/search/ui/SearchContent.tsx
  src/features/reward/search/ui/SearchResult.tsx
  src/shared/store/cafeDetailStore.ts
  src/shared/ui/modal/Modal.tsx
Labels: 🐛 bug, 🔧 fix
